[package]
name = "test_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_opt2doc = { path = "../derive_opt2doc" }
once_cell = "1.19.0"
